trigger:
- main

pool:
  name: COMP367-DevOps Agent

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'todoAPI3'
    publishLocation: 'Container'

- task: DotNetCoreCLI@2
  displayName: dotnet pack
  inputs:
    command: pack
    versioningScheme: byPrereleaseNumber

- task: NuGetAuthenticate@1  # Authenticate with Azure Artifacts using version 1

- task: PowerShell@2
  displayName: 'Push NuGet'
  inputs:
    targetType: 'inline'
    script: |
      dotnet nuget push "$(Build.ArtifactStagingDirectory)/**/*.nupkg" `
        --source "https://pkgs.dev.azure.com/nneedha1/Lab4CD/_packaging/lab4cdfeed/nuget/v3/index.json" `
        --api-key AzureDevOps `
        --skip-duplicate
    